/* File generated by ToTargetConfigFile.xsl */

#define XKCP_has_Sponge_Keccak
#define XKCP_has_TurboSHAKE
#define XKCP_has_FIPS202
#define XKCP_has_SP800_185
#define XKCP_has_Duplex_Keccak
#define XKCP_has_OD_Keccak
#define XKCP_has_ShakingUpAE
#define XKCP_has_PRG_Keccak
#define XKCP_has_KangarooTwelve
#define XKCP_has_Kravatte
#define XKCP_has_Xoofff
#define XKCP_has_Xoodyak
#define XKCP_has_KeccakP1600
#define XKCP_has_x86_64_CPU_detection
#define XKCP_has_KeccakP1600times2
#define XKCP_has_KeccakP1600times4
#define XKCP_has_KeccakP1600times8
#define XKCP_has_Xoodoo
#define XKCP_has_x86_64_CPU_detection
#define XKCP_has_Xoodootimes4
#define XKCP_has_Xoodootimes8
#define XKCP_has_Xoodootimes16
